// <auto-generated />
using System;
using DataAccesLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccesLayer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230918031937_MigracionIni")]
    partial class MigracionIni
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccesLayer.Models.Categorias", b =>
                {
                    b.Property<int>("id_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Categoria"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Categoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("DataAccesLayer.Models.ClientesPreferenciales", b =>
                {
                    b.Property<int>("id_Cli_Preferencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Cli_Preferencial"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("saldo")
                        .HasColumnType("real");

                    b.Property<int>("telefono")
                        .HasColumnType("int");

                    b.HasKey("id_Cli_Preferencial");

                    b.ToTable("Cliente_Preferencial");
                });

            modelBuilder.Entity("DataAccesLayer.Models.Ingredientes", b =>
                {
                    b.Property<int>("id_Ingrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Ingrediente"));

                    b.Property<int?>("id_Categoria")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.HasKey("id_Ingrediente");

                    b.ToTable("Ingrediente");
                });

            modelBuilder.Entity("DataAccesLayer.Models.Mesas", b =>
                {
                    b.Property<int>("id_Mesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Mesa"));

                    b.Property<bool>("enUso")
                        .HasColumnType("bit");

                    b.HasKey("id_Mesa");

                    b.ToTable("Mesa");
                });

            modelBuilder.Entity("DataAccesLayer.Models.Pedidos", b =>
                {
                    b.Property<int>("id_Pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Pedido"));

                    b.Property<bool>("estadoPago")
                        .HasColumnType("bit");

                    b.Property<bool>("estadoProceso")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_ingreso")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("hora_ingreso")
                        .HasColumnType("time");

                    b.Property<int>("id_Cli_Preferencial")
                        .HasColumnType("int");

                    b.Property<int>("id_Mesa")
                        .HasColumnType("int");

                    b.Property<int>("numero_movil")
                        .HasColumnType("int");

                    b.Property<bool>("pago")
                        .HasColumnType("bit");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("valorPedido")
                        .HasColumnType("real");

                    b.HasKey("id_Pedido");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("DataAccesLayer.Models.Pedidos_Productos", b =>
                {
                    b.Property<int>("id_Pedido")
                        .HasColumnType("int");

                    b.Property<int>("id_Producto")
                        .HasColumnType("int");

                    b.HasKey("id_Pedido", "id_Producto");

                    b.ToTable("Pedido_Producto");
                });

            modelBuilder.Entity("DataAccesLayer.Models.Productos", b =>
                {
                    b.Property<int>("id_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Producto"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("precio")
                        .HasColumnType("real");

                    b.HasKey("id_Producto");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("DataAccesLayer.Models.Productos_Ingredientes", b =>
                {
                    b.Property<int>("id_Producto")
                        .HasColumnType("int");

                    b.Property<int>("id_Ingrediente")
                        .HasColumnType("int");

                    b.HasKey("id_Producto", "id_Ingrediente");

                    b.ToTable("Producto_Ingrediente");
                });
#pragma warning restore 612, 618
        }
    }
}
